name: CD

on:
  push:
    branches: [ develop ]
  
jobs:

  scm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  build:
    needs: [scm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Build with Maven
        run: mvn -B package -DskipTests=true --file pom.xml

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: runner test
        run: mvn clean verify -DskipTests=true

  package:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: package application
        run: |
          mvn clean install -DskipTests=true
